Repository rancher/rke, pull requests merged in 2021-11, with the labels that each got.

#2737 [release/v1.3] update kdm
  data/bindata.go
  data/data.json
Labels: status/auto-approved

#2701 Update cluster.parseCustomConfig function to proper decode custom EncryptionConfiguration
  cluster/encryption.go
Labels: [zube]: Review

#2751 Supporting Windows 1.22
  data/bindata.go
  data/data.json
Labels: kind/bug-qa

#2754 [release/v1.3] go generate
  data/bindata.go
  data/data.json
Labels: status/auto-approved
